### ISSUE TITLE
NullPointerException PlayerEquipmentModule.java:19 list.add

### ISSUE THREAD

**Issue by Aerath** [asaskevich/SmartCursor#8]
> com.asaskevich.smartcursor.RenderHandler:**renderGameOverlay:242**: java.lang.NullPointerException
> java.lang.NullPointerException
>     at com.asaskevich.smartcursor.modules.player.PlayerEquipmentModule.process(**PlayerEquipmentModule.java:19**)
>     at com.asaskevich.smartcursor.render.RenderPlayer.render(RenderPlayer.java:42)
>     at com.asaskevich.smartcursor.RenderHandler.renderGameOverlay(RenderHandler.java:153)
>     at cpw.mods.fml.common.eventhandler.ASMEventHandler_13_RenderHandler_renderGameOverlay_RenderGameOverlayEvent.invoke(.dynamic)
>     at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
>     at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
>     at net.minecraftforge.client.GuiIngameForge.renderHUDText(GuiIngameForge.java:699)
>     at net.minecraftforge.client.GuiIngameForge.func_73830_a(GuiIngameForge.java:155)
>     at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1038)
>     at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:990)
>     at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
>     at net.minecraft.client.main.Main.main(SourceFile:148)
>     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
>     at java.lang.reflect.Method.invoke(Unknown Source)
>     at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
>     at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
>     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
>     at java.lang.reflect.Method.invoke(Unknown Source)
>     at magic.launcher.Launcher.main(SourceFile:214)

``` java
public void process(List<String> list, EntityPlayer player) {
/*17*/  ItemStack[] items = player.getLastActiveItems();
/*18*/  boolean h = player.getHeldItem() != null;
/*19*/  for (ItemStack item : items)
/*20*/      if (item != null) h = true;
/*21*/  if (h) {
/*22*/      list.add(EnumChatFormatting.GRAY + StatCollector.translateToLocal("smartcursor.player.equipment"));
```

list is never initialized with something like 

``` java
list = new ArrayList<String>();
```

**Comment by asaskevich** [comment]
This list described here: https://github.com/asaskevich/SmartCursor/blob/master/java/com/asaskevich/smartcursor/render/RenderPlayer.java#L39 and passed to module here: https://github.com/asaskevich/SmartCursor/blob/master/java/com/asaskevich/smartcursor/render/RenderPlayer.java#L43

Problem was fixed after initialization of list? I can't merge PL now because I'm not sure that problem is fixed. Can you provide more information (something about player you looking at, etc.) ?

**Comment by Aerath** [comment]
Sorry, it seems I was not careful enough when reading this part of the code (damn flu and fever). My apologies. Error was fixed after adding this line, and returned after having removed the same line (for verification purposes), so I assumed it was the cause but since list is correctly initialized, it shouldn't throw NPE with or without this PL. Maybe a weird side-effect ?
Any way, I will try to find the cause of the error in the next two weeks.
Thank you for answering !

**Comment by asaskevich** [comment]
Not a problem, I waiting for your report. Not sure about side-effect - here screenshot  (https://camo.githubusercontent.com/d698c6b6b313c0320d3ade617531b2ebb74cf815/687474703a2f2f7333302e706f7374696d672e6f72672f7839373279616270742f323031345f30385f30385f31315f30385f33322e706e67) and all works fine. Maybe some mod caused this issue? I would like to hear about installed mods, equipment, that was at the player in moment of NPE or anything else I forgot.

**Comment by asaskevich** [comment]
@Aerath is it make sense at the current moment?

**Comment by Aerath** [comment]
Sorry for not going back to you, I guess I forgot it ...
Anyway, I'm not using your mod anymore, as the corresponding project's development as long been stopped. Thank you for your consideration and your time.
